#!/bin/sh
declare -a cows=(  
        "beavis.zen"
        "blowfish"
        "bong"
        "bud-frogs" 
        "bunny"
        "cheese"
        "cower"
        "daemon"
        "default"
        "dragon"
        "dragon-and-cow"
        "elephant"
        "elephant-in-snake"
        "eyes"
        "flaming-sheep"
        "ghostbusters"
        "hellokitty"
        "kiss"
        "kitty"
        "koala"
        "kosh"
        "luke-koala"
        "meow"
        "milk"
        "moofasa"
        "moose"
        "mutilated"
        "ren"
        "satanic"
        "sheep"
        "skeleton"
        "small"
        "stegosaurus"
        "stimpy"
        "supermilker"
        "surgery"
        "three-eyes"
        "turkey"
        "turtle"
        "tux"
        "udder"
        "vader"
        "vader-koala"
        "www"
)
rand="$(shuf -i 0-2 | head -n1)"

for i in "${cows[@]}"
    do
        i="$(shuf -i 0-43 | head -n1)"
        if [ $rand == 1 ] ; then
            command=$(fortune | cowsay -f "${cows["$i"]}" | lolcat); echo "$command"; break
        else
            command=$(fortune | cowsay -f "${cows["$i"]}"); echo "$command"; break
        fi
    done
