#!/bin/sh
cd ~/.config/
mkdir neofetch/ dunst/ dwm/ dmenu/ flameshot/ htop/ openbox/ picom/ qtile/ redshift/ rofi/ tabliss/ youtube/ sway/ cool-retro-term/
cd ~/sweet-dots/
\cp -r obmenu-generator/ ~/.config/obmenu-generator
\cp neofetch/config.conf ~/.config/neofetch/
\cp cool-retro-term/cool-retro-term.json ~/.config/cool-retro-term/
\cp dunst/dunstrc ~/.config/dunst/
\cp dwm/* ~/.config/dwm/
\cp dmenu/* ~/.config/dmenu
\cp flameshot/flameshot.ini ~/.config/flameshot/
\cp htop/htoprc ~/.config/htop/
\cp -r lxpanel/ ~/.config/lxpanel
\cp openbox/* ~/.config/openbox/
\cp picom/picom.conf ~/.config/picom/
\cp -r qtile/ ~/.config/qtile/
\cp redshift/redshift.conf ~/.config/redshift/
\cp rofi/config.rasi ~/.config/rofi/
\cp tabliss/tabliss.json ~/.config/tabliss/
\cp sway/config ~/.config/sway
\cp youtube/config ~/.config/youtube
\cp .xinitrc .profile .bashrc .bash_profile .bash_aliases .Xresources .vimrc .xprofile ~/
\cp -r .vim/ ~/
