#!/bin/sh
cd ~/.config/
\cp -r alacritty/ dunst/ dwm/ dmenu/ flameshot/ htop/ lxpanel/ neofetch/ obmenu-generator/ openbox/ picom/ qtile/ redshift/ rofi/ tabliss/ youtube/ mpv/ ~/sweet-dots/
cd
\cp .bashrc .vimrc .xinitrc .profile .xprofile .bash_profile .Xresources sweet-dots/
