#!/usr/bin/env bash
cd ~/Music
echo "Do you want to shuffle the playlist? (Y/n)"
read shuffle
[[ "$shuffle" == "y" ]] && mpv "$(ls -d */ | fzf)"* --shuffle --vo=null && exit
[[ "$shuffle" == "Y" ]] && mpv "$(ls -d */ | fzf)"* --shuffle --vo=null && exit
[[ "$shuffle" == "" ]] && mpv "$(ls -d */ | fzf)"* --shuffle --vo=null && exit
mpv "$(ls -d */ | fzf)"* --vo=null && exit
