#!/bin/sh
cd ~/.config/
\cp -r alacritty/ dunst/ dwm/ dmenu/ flameshot/ htop/ lxpanel/ neofetch/ obmenu-generator/ openbox/ picom/ qtile/ redshift/ rofi/ tabliss/ youtube/ mpv/ sway/ cool-retro-term/ ~/git/sweet-dots/
cd
\cp .bashrc .bash_aliases .vimrc .xinitrc .profile .xprofile .bash_profile .Xresources git/sweet-dots/
