#!/usr/bin/env bash
cd ~/Music
#echo "Do you want to shuffle the playlist? (Y/n)"
#read shuffle
#[[ "$shuffle" == "y" ]] && mpv "$(ls -d */ | fzf)"* --shuffle  && exit
#[[ "$shuffle" == "Y" ]] && mpv "$(ls -d */ | fzf)"* --shuffle  && exit
#[[ "$shuffle" == "" ]] && mpv "$(ls -d */ | fzf)"* --shuffle  && exit
mpv "$(ls -d */ | fzf)"* --shuffle --input-ipc-server=/tmp/mpvsocket && exit
